[package]
name = "dama-gb"
version = "0.0.1"
edition = "2021"
readme = "README.md"
repository = "https://github.com/DagothBob/Dama.GB"

[dependencies]
bitfield = "0.14.0"
paste = "1.0.14"
sdl2 = "0.35.2"